modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/TeamFelnull/IamMusicPlayer/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "iammusicplayer"
version = "${version}"
displayName = "Iam Music Player"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/iammusicplayer"
updateJSONURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/version_check.json"
authors = "MORIMORI0317, nin8995"
credits = "FelNull developers"
logoFile = "logo.png"
description = '''
Thank you for downloading!
This mod is The Ikisugi Music Player MOD.
'''
[modproperties.iammusicplayer]
catalogueImageIcon = "icon.png"

[[dependencies.iammusicplayer]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "architectury"
mandatory = true
versionRange = "[3.7.22,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.57,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "otyacraftengine"
mandatory = true
versionRange = "[2.3,)"
ordering = "AFTER"
side = "BOTH"