modLoader = "javafml"
loaderVersion = "[46,)"
license = "GNU LGPLv3"

[[mods]]
modId = "iammusicplayer"
version = "0.6 - Fork of iammusic 3.22.0-alpha.3"
displayName = "Create - Songs and Speakers (Iam Music Player Fork)"
displayURL = "https://legacy.curseforge.com/minecraft/mc-mods/create-songs-and-speakers-iam-music-player-fork"
authors = "Billnotic"
credits = "MORIMORI0317, nin8995, and the other FelNull developers for their insanely good music mod."
description = '''
Modifies the ikisugi music player mod for better compatibility with Create.
'''
logoFile = "logo.png"

[[dependencies.iammusicplayer]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.0.99,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "otyacraftengine"
mandatory = true
versionRange = "[3.7.0-alpha.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"