modLoader="javafml"
loaderVersion="[28,)" 
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="iammusicplayer"
version="${file.jarVersion}" 
displayName="Iam Music Player"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/version_check.json" 
displayURL="" 
logoFile="n.png" 
credits=""
authors="TeamFelNull" 
description='''
Thank you for downloading!
'''
